// this is an example of a pipeline.yml for this project to show how i would go about doing a basic build

resources:
- icon: github
  name: git
  source:
    branch: main
    private_key: ((example))
    uri: git@github.com:izabela01/movie-menu.git
  type: git

- icon: docker
  name: node
  type: registry-image
  source:
    repository: node
    tag: 16.19.0

jobs:
- name: build
  plan:
  - get: git
  - get: node

  - task: webappbuild
    image: node
    config:
      inputs:
      - name: git
      platform: linux
      outputs:
      - name: git
      run:
        args:
        - -exc
        - |
        npm run build
        path: /bin/sh